pub mod error;
pub mod events;
pub mod metadata;
pub mod pool;
pub mod probe;
pub mod segment;
pub mod storage;
pub mod throttle;
pub mod worker;
pub mod downloader;

pub use error::CoreError;
pub use events::{ChunkInitInfo, DownloadEvent};
pub use metadata::{delete_state, load_state, metadata_path, save_state, DownloadState, SegmentState};
pub use pool::{ActiveSegment, SegmentPool};
pub use probe::{probe_url, ProbeInfo};
pub use segment::{calculate_segments, Segment};
pub use storage::{preallocate_file, ChunkWriter};
pub use throttle::{parse_speed_limit, BandwidthLimiter};
pub use downloader::{default_download_dir, download_file, DownloadOptions};
